const BOOKS = {
  project1a: {
    id: 'project1a',
    name: 'The New Italian Project 1a',
    amount: 4900,
    imagePath: '/img/books/new-italian-project-1a.jpeg',
  },
  project1b: {
    id: 'project1b',
    name: 'The New Italian Project 1b',
    amount: 4900,
    imagePath: '/img/books/new-italian-project-1b.webp',
  },
};

const CLASSES = {
  'fall-2026-thu-beg': {
    id: 'fall-2026-thu-beg',
    name: 'Fall 2026 Italian Class - Beginner Thursday',
    level: 'Beginner',
    format: 'In person',
    pagePath: '/news/2026/06/beginner-adult-italian-classes-fall-2026/',
    anchor: 'thu-beg',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1a',
  },
  'fall-2026-sat-beg': {
    id: 'fall-2026-sat-beg',
    name: 'Fall 2026 Italian Class - Beginner Saturday',
    level: 'Beginner',
    format: 'In person',
    pagePath: '/news/2026/06/beginner-adult-italian-classes-fall-2026/',
    anchor: 'sat-beg',
    fullAmount: 54000,
    monthlyAmount: 11880,
    bookId: 'project1a',
  },
  'fall-2026-wed-beg': {
    id: 'fall-2026-wed-beg',
    name: 'Fall 2026 Italian Class - Beginner Wednesday',
    level: 'Beginner',
    format: 'In person',
    pagePath: '/news/2026/06/beginner-adult-italian-classes-fall-2026/',
    anchor: 'wed-beg',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1a',
  },
  'fall-2026-thu-beg-online': {
    id: 'fall-2026-thu-beg-online',
    name: 'Fall 2026 Italian Class - Beginner Thursday Online',
    level: 'Beginner',
    format: 'Online',
    pagePath: '/news/2026/06/beginner-adult-italian-classes-fall-2026/',
    anchor: 'thu-beg-online',
    fullAmount: 54400,
    monthlyAmount: 11968,
  },
  'fall-2026-mon-int': {
    id: 'fall-2026-mon-int',
    name: 'Fall 2026 Italian Class - Intermediate Monday',
    level: 'Intermediate',
    format: 'In person',
    pagePath: '/news/2026/06/intermediate-intermediate-advanced-adult-italian-classes-fall-2026/',
    anchor: 'mon-int',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1b',
  },
  'fall-2026-mon-int-adv': {
    id: 'fall-2026-mon-int-adv',
    name: 'Fall 2026 Italian Class - Intermediate-Advanced Monday',
    level: 'Intermediate-Advanced',
    format: 'In person',
    pagePath: '/news/2026/06/intermediate-intermediate-advanced-adult-italian-classes-fall-2026/',
    anchor: 'mon-int-adv',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1b',
  },
  'fall-2026-wed-beg-int': {
    id: 'fall-2026-wed-beg-int',
    name: 'Fall 2026 Italian Class - Beginner-Intermediate Wednesday',
    level: 'Beginner-Intermediate',
    format: 'In person',
    pagePath: '/news/2026/06/intermediate-intermediate-advanced-adult-italian-classes-fall-2026/',
    anchor: 'wed-beg-int',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1a',
  },
  'fall-2026-thu-beg-int': {
    id: 'fall-2026-thu-beg-int',
    name: 'Fall 2026 Italian Class - Beginner-Intermediate Thursday',
    level: 'Beginner-Intermediate',
    format: 'In person',
    pagePath: '/news/2026/06/intermediate-intermediate-advanced-adult-italian-classes-fall-2026/',
    anchor: 'thu-beg-int',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1a',
  },
  'fall-2026-mon-beg-int-online': {
    id: 'fall-2026-mon-beg-int-online',
    name: 'Fall 2026 Italian Class - Beginner-Intermediate Monday Online',
    level: 'Beginner-Intermediate',
    format: 'Online',
    pagePath: '/news/2026/06/intermediate-intermediate-advanced-adult-italian-classes-fall-2026/',
    anchor: 'mon-beg-int-online',
    fullAmount: 54400,
    monthlyAmount: 11968,
  },
  'fall-2026-tue-int-online': {
    id: 'fall-2026-tue-int-online',
    name: 'Fall 2026 Italian Class - Intermediate Tuesday Online',
    level: 'Intermediate',
    format: 'Online',
    pagePath: '/news/2026/06/intermediate-intermediate-advanced-adult-italian-classes-fall-2026/',
    anchor: 'tue-int-online',
    fullAmount: 54400,
    monthlyAmount: 11968,
  },
  'fall-2026-mon-adv': {
    id: 'fall-2026-mon-adv',
    name: 'Fall 2026 Italian Class - Advanced Monday',
    level: 'Advanced',
    format: 'In person',
    pagePath: '/news/2026/06/advanced-conversation-adult-italian-classes-fall-2026/',
    anchor: 'mon-adv',
    fullAmount: 57600,
    monthlyAmount: 12672,
    bookId: 'project1b',
  },
  'fall-2026-thu-conv': {
    id: 'fall-2026-thu-conv',
    name: 'Fall 2026 Italian Class - Conversation Thursday',
    level: 'Conversation',
    format: 'In person',
    pagePath: '/news/2026/06/advanced-conversation-adult-italian-classes-fall-2026/',
    anchor: 'thu-conv',
    fullAmount: 57600,
    monthlyAmount: 12672,
  },
};

module.exports = {
  BOOKS,
  CLASSES,
};
